FROM node:10-slim as pre-build
COPY package*.json ./
RUN npm version 0.0.1

FROM node:10-slim

WORKDIR /app/

COPY --from=pre-build package*.json ./

RUN npm install --production

COPY src ./

CMD ["node", "app.js"]
